"use client";
/* eslint-disable @typescript-eslint/no-unused-expressions -- Setの追加・削除を簡潔に切り替える暗記UI */

import { useState } from "react";
import { categoryLabels, electrochemistryCards, massLabels, type ElectrochemistryCard } from "@/data/electrochemistry";

type View="cards"|"memory"|"compare";
const comparisonPresets:Record<string,[string,string]>={"ボルタ電池 vs ダニエル電池":["volta","daniel"],"電池 vs 電気分解":["volta","water-electrolysis"],"鉛蓄電池 放電 vs 充電":["lead-discharge","lead-charge"],"CuSO₄：Pt vs Cu電極":["cuso4-pt","cuso4-cu"],"NaCl：水溶液 vs 融解塩":["nacl-aq","nacl-molten"],"一次電池 vs 二次電池":["manganese","lithium-ion"]};
const polarity=(value:"positive"|"negative")=>value==="positive"?"正極（＋）":"負極（−）";
const role=(value:"anode"|"cathode")=>value==="anode"?"陽極":"陰極";

function MiniDiagram({card}:{card:ElectrochemistryCard}){const left=card.electrodes[0],right=card.electrodes[1];return <div className="ec-diagram"><div className="ec-wire">{card.mode==="galvanic-cell"?"e⁻ 外部回路":"直流電源"}</div><div className={`ec-electrode left ${left.reactionType}`}><b>{left.label}</b><span>{left.material}</span><small>{left.products.join("・")}</small></div><div className="ec-liquid"><b>{card.electrolytes.join("／")}</b><span>電解液中はイオンが移動</span></div><div className={`ec-electrode right ${right.reactionType}`}><b>{right.label}</b><span>{right.material}</span><small>{right.products.join("・")}</small></div></div>}

function ReactionPanel({card,hidden}:{card:ElectrochemistryCard;hidden:Set<string>}){return <div className="ec-details">{card.electrodes.map(item=><section className={item.reactionType} key={item.electrodeRole}><h4>{hidden.has("electrodes")?"？？？":`${item.label}・${role(item.electrodeRole)}・${polarity(item.polarity)}`}</h4><strong>{item.reactionType==="oxidation"?"酸化":"還元"}</strong><p className="ec-equation">{hidden.has("half")?"半反応式：？？？":item.equation}</p><p><b>材質：</b>{hidden.has("electrodes")?"？？？":item.material}</p><p><b>生成：</b>{hidden.has("products")?"？？？":item.products.join("・")}</p><p><b>質量：</b>{hidden.has("mass")?"？？？":massLabels[item.massChange]}</p>{item.observations?.map(text=><small key={text}>{text}</small>)}</section>)}</div>}

function FullCard({card,memory=false}:{card:ElectrochemistryCard;memory?:boolean}){const [detail,setDetail]=useState(false);const [hidden,setHidden]=useState<Set<string>>(new Set(memory?["electrolyte","electrodes","half","overall","products","mass","solution","electron"]:[]));const toggle=(key:string)=>setHidden(current=>{const next=new Set(current);next.has(key)?next.delete(key):next.add(key);return next;});return <article className="ec-card"><header><span>{categoryLabels[card.category]}</span><h3>{card.name}</h3></header><MiniDiagram card={card}/><div className="ec-card-summary"><p><b>電解質：</b>{hidden.has("electrolyte")?"？？？":card.electrolytes.join("／")}</p><p className="ec-overall"><b>全反応：</b>{hidden.has("overall")?"？？？":card.overallEquation}</p></div>{memory&&<div className="ec-hide-controls">{[["electrolyte","電解質"],["electrodes","電極"],["half","半反応式"],["overall","全反応"],["products","生成物"],["mass","質量"],["solution","溶液"],["electron","電子"]].map(([key,label])=><button className={hidden.has(key)?"hidden":""} onClick={()=>toggle(key)} key={key}>{label}</button>)}<button onClick={()=>setHidden(new Set())}>答えをすべて表示</button></div>}<button className="ec-detail-toggle" onClick={()=>setDetail(value=>!value)}>{detail?"詳細を閉じる":"カードをめくって詳細を見る"}</button>{detail&&<div className="ec-card-back"><ReactionPanel card={card} hidden={hidden}/><dl><div><dt>電子</dt><dd>{hidden.has("electron")?"？？？":card.electronFlow}</dd></div><div><dt>イオン移動</dt><dd>{card.ionMovement.join("／")}</dd></div><div><dt>溶液変化</dt><dd>{hidden.has("solution")?"？？？":card.solutionChanges.join("／")}</dd></div><div><dt>重要</dt><dd>{card.keyPoints.join("／")}</dd></div><div className="mistake"><dt>よくある誤答</dt><dd>{card.commonMistakes.join("／")}</dd></div></dl></div>}</article>}

function CompareCard({card}:{card:ElectrochemistryCard}){return <article className="ec-compare-card"><span>{categoryLabels[card.category]}</span><h3>{card.name}</h3><ReactionPanel card={card} hidden={new Set()}/><p><b>全反応：</b>{card.overallEquation}</p><p><b>生成物：</b>{card.electrodes.flatMap(e=>e.products).join("・")}</p><p><b>溶液：</b>{card.solutionChanges.join("／")}</p></article>}

export function ElectrochemistryLab(){const [view,setView]=useState<View>("cards");const [index,setIndex]=useState(0);const [preset,setPreset]=useState(Object.keys(comparisonPresets)[0]);const card=electrochemistryCards[index];const pair=comparisonPresets[preset].map(id=>electrochemistryCards.find(item=>item.id===id)!);return <div className="ec-lab"><div className="gas-mode-tabs">{([['cards','カード'],['memory','暗記モード'],['compare','比較']] as Array<[View,string]>).map(([value,label])=><button className={view===value?"active":""} onClick={()=>setView(value)} key={value}>{label}</button>)}</div>{view!=="compare"?<><div className="ec-card-nav"><button onClick={()=>setIndex((index-1+electrochemistryCards.length)%electrochemistryCards.length)}>←</button><label><span>{index+1} / {electrochemistryCards.length}</span><select value={index} onChange={event=>setIndex(Number(event.target.value))}>{electrochemistryCards.map((item,i)=><option value={i} key={item.id}>{item.order}. {item.name}</option>)}</select></label><button onClick={()=>setIndex((index+1)%electrochemistryCards.length)}>→</button></div><FullCard key={`${card.id}-${view}`} card={card} memory={view==="memory"}/></>:<div className="ec-compare"><label>比較プリセット<select value={preset} onChange={event=>setPreset(event.target.value)}>{Object.keys(comparisonPresets).map(name=><option key={name}>{name}</option>)}</select></label><div>{pair.map(item=><CompareCard card={item} key={item.id}/>)}</div></div>}</div>}
