"use client";

import { useEffect, useMemo, useState } from "react";
import { electrochemistryCards } from "@/data/electrochemistry";
import { electrochemistrySimulations } from "@/data/electrochemistrySimulations";

export function ElectrochemistrySimulator({initialCardId}:{initialCardId?:string}){
 const initial=Math.max(0,electrochemistrySimulations.findIndex(item=>item.sourceCardId===initialCardId));const [index,setIndex]=useState(initial);const [step,setStep]=useState(0);const [playing,setPlaying]=useState(false);const [speed,setSpeed]=useState<"slow"|"normal"|"fast">("normal");
 const [showLabels,setShowLabels]=useState(true);const [showElectrons,setShowElectrons]=useState(true);const [showIons,setShowIons]=useState(true);const [showEquations,setShowEquations]=useState(true);const simulation=electrochemistrySimulations[index],card=electrochemistryCards.find(item=>item.id===simulation.sourceCardId)!;
 useEffect(()=>{if(!playing)return;const delay={slow:1800,normal:1000,fast:500}[speed];const timer=window.setInterval(()=>setStep(current=>{if(current>=simulation.timeline.length){setPlaying(false);return current;}return current+1;}),delay);return()=>window.clearInterval(timer);},[playing,simulation.timeline.length,speed]);
 const active=useMemo(()=>simulation.timeline.slice(0,step).flatMap(item=>item.effects),[simulation,step]);const has=(type:string,target?:string)=>active.some(effect=>effect.type===type&&(!target||effect.target===target));const gas=(target:string)=>active.find(effect=>effect.type==="gas-bubbles"&&effect.target===target)?.species;const progress=Math.round(step/simulation.timeline.length*100);
 const change=(next:number)=>{setIndex(next);setStep(0);setPlaying(false);};
 return <div className="simulator-shell"><header><div><span>{card.mode==="galvanic-cell"?"電池":"電気分解・充電"}</span><h3>{simulation.title}</h3><p>{card.keyPoints.join("／")}</p></div><select value={index} onChange={event=>change(Number(event.target.value))}>{electrochemistrySimulations.map((item,i)=><option value={i} key={item.id}>{i+1}. {item.title}</option>)}</select></header><div className="simulation-layout"><div className={`animated-cell ${playing?"playing":""}`}><svg viewBox="0 0 760 430" role="img" aria-label={`${simulation.title}のシミュレーション`}>
  <path className="sim-wire" d="M180 110 V45 H580 V110"/><rect className="sim-power" x="340" y="25" width="80" height="40" rx="7"/><text x="380" y="50" textAnchor="middle">{card.mode==="galvanic-cell"?"外部回路":"直流電源"}</text>
  {showElectrons&&active.some(e=>e.type==="electron-flow")&&[0,1,2,3].map(i=><circle className="electron-dot" cx={220+i*85} cy="45" r="7" key={i}/>) }
  <path className="sim-vessel" d="M80 150 V390 H680 V150"/><rect x="84" y="170" width="592" height="216" fill={has("color-change","solution")?`color-mix(in srgb, #4aa7e8 ${100-progress}%, #d8effc)`:has("color-change","left-solution")||has("color-change","right-solution")?"#dfeaff":simulation.initialState.solutionColorLeft} opacity=".62"/>
  <rect className={`sim-electrode ${has("electrode-dissolve","left")?"dissolving":""}`} x={has("electrode-dissolve","left")?"164":"155"} y="105" width={has("electrode-dissolve","left")?"32":"50"} height="230"/><rect className={`sim-electrode ${has("electrode-dissolve","right")?"dissolving":""}`} x="555" y="105" width={has("electrode-dissolve","right")?"32":"50"} height="230"/>
  {has("deposit-growth","left")||has("mass-change","left")?<rect className="deposit copper" x="148" y="180" width="64" height={40+progress*.8}/>:null}{has("deposit-growth","right")||has("mass-change","right")?<rect className="deposit copper" x="548" y="180" width="64" height={40+progress*.8}/>:null}
  {(["left","right"] as const).flatMap(target=>gas(target)?[0,1,2,3,4].map(i=><g key={`${target}-${i}`}><circle className="gas-bubble" cx={(target==="left"?175:580)+(i%2)*18} cy={175-i*28} r={5+i%3}/><text x={target==="left"?125:620} y="155" className="gas-label">{gas(target)}</text></g>):[])}
  {showIons&&active.some(e=>e.type==="cation-flow")&&[0,1,2].map(i=><g className="ion cation" key={`c${i}`}><circle cx={300+i*55} cy={260+i%2*35} r="13"/><text x={300+i*55} y={265+i%2*35} textAnchor="middle">＋</text></g>)}{showIons&&active.some(e=>e.type==="anion-flow")&&[0,1,2].map(i=><g className="ion anion" key={`a${i}`}><circle cx={450-i*55} cy={315-i%2*35} r="13"/><text x={450-i*55} y={320-i%2*35} textAnchor="middle">−</text></g>)}
  {has("precipitation","anode-bottom")&&[0,1,2,3,4,5].map(i=><circle className="anode-mud" cx={545+i*14} cy={374-i%2*5} r="6" key={i}/>)}
  {showLabels&&<><text x="180" y="365" textAnchor="middle">{simulation.initialState.leftElectrodeLabel}</text><text x="580" y="365" textAnchor="middle">{simulation.initialState.rightElectrodeLabel}</text><text x="380" y="410" textAnchor="middle">{simulation.initialState.solutionLabel}</text></>}
 </svg><div className="sim-progress"><span style={{width:`${progress}%`}}/><b>{progress}%</b></div></div><aside><h4>Step {Math.max(step,1)} / {simulation.timeline.length}</h4><p>{step===0?"再生またはステップ実行で開始します。":simulation.timeline[step-1].description}</p>{showEquations&&<><section className="oxidation"><b>陽極・酸化</b><code>{card.electrodes.find(item=>item.electrodeRole==="anode")?.equation}</code></section><section className="reduction"><b>陰極・還元</b><code>{card.electrodes.find(item=>item.electrodeRole==="cathode")?.equation}</code></section><section><b>全反応</b><code>{card.overallEquation}</code></section></>}{step>0&&simulation.timeline[step-1].effects.map((effect,i)=><small key={i}>{effect.note}</small>)}</aside></div><div className="simulation-controls"><button onClick={()=>setPlaying(true)}>▶ 再生</button><button onClick={()=>setPlaying(false)}>⏸ 一時停止</button><button onClick={()=>{setStep(0);setPlaying(false);}}>↺ リセット</button><button onClick={()=>setStep(current=>Math.min(simulation.timeline.length,current+1))}>1ステップ</button><label>速度<select value={speed} onChange={event=>setSpeed(event.target.value as typeof speed)}><option value="slow">遅い</option><option value="normal">普通</option><option value="fast">速い</option></select></label><label><input type="checkbox" checked={showLabels} onChange={e=>setShowLabels(e.target.checked)}/>ラベル</label><label><input type="checkbox" checked={showElectrons} onChange={e=>setShowElectrons(e.target.checked)}/>電子</label><label><input type="checkbox" checked={showIons} onChange={e=>setShowIons(e.target.checked)}/>イオン</label><label><input type="checkbox" checked={showEquations} onChange={e=>setShowEquations(e.target.checked)}/>反応式</label></div><div className="sim-keypoints"><b>重要ポイント</b>{card.keyPoints.map(point=><span key={point}>{point}</span>)}<b>注意</b>{card.commonMistakes.map(point=><span key={point}>{point}</span>)}</div></div>;
}
