"use client";

import { useMemo, useState } from "react";
import { electrochemistryCards, massLabels, type ElectrochemistryCard } from "@/data/electrochemistry";
import { getBatteryCompositionRows, reactionReason } from "@/lib/electrochemistryPrint";

type Scope="battery"|"electrolysis"|"both";type QuestionType="written"|"fill"|"mixed";type PrintMode="problem"|"answer";
const isBattery=(card:ElectrochemistryCard)=>card.mode==="galvanic-cell"||card.mode==="charging";
function BatteryComposition({card}:{card:ElectrochemistryCard}){return <section className="print-battery-composition" aria-label="電池の構成"><h3>与えられた構成</h3><dl>{getBatteryCompositionRows(card).map(row=><div key={row.label}><dt>{row.label}</dt><dd>{row.value}</dd></div>)}</dl></section>}
function StaticDiagram({card,hide}:{card:ElectrochemistryCard;hide:boolean}){return <svg className="quiz-device-diagram" viewBox="0 0 700 260"><path d="M150 85 V35 H550 V85" fill="none" stroke="#263653" strokeWidth="4"/><rect x="315" y="18" width="70" height="35" rx="6" fill="white" stroke="#263653" strokeWidth="2"/><text x="350" y="41" textAnchor="middle">{card.mode==="galvanic-cell"?"回路":"電源"}</text><path d="M70 100 V235 H630 V100" fill="#dff1ff" stroke="#5b91bd" strokeWidth="4"/><rect x="130" y="75" width="40" height="125" fill="#596477"/><rect x="530" y="75" width="40" height="125" fill="#596477"/><text x="150" y="220" textAnchor="middle">{hide?"電極 A":card.electrodes[0].material}</text><text x="550" y="220" textAnchor="middle">{hide?"電極 B":card.electrodes[1].material}</text><text x="350" y="175" textAnchor="middle">{hide?"電解液（　　　　　　）":card.electrolytes.join("／")}</text>{card.id==="daniel"&&<><line x1="350" y1="90" x2="350" y2="210" stroke="#93734e" strokeWidth="9" strokeDasharray="7 5"/><text x="350" y="80" textAnchor="middle">{hide?"（　　　）":"塩橋"}</text></>}</svg>}
function ProblemPage({card,index,type}:{card:ElectrochemistryCard;index:number;type:QuestionType}){const fill=type==="fill"||(type==="mixed"&&index%2===1),battery=isBattery(card);return <article className="print-quiz-page problem-page"><header><h1>電池・電気分解 小テスト</h1><span>第{index+1}問　氏名　　　　　　　　　</span></header><h2>{fill&&!battery?"次の装置図の空欄を埋めなさい。":`次の図は「${card.name}」を示す。問いに答えなさい。`}</h2>{battery&&<BatteryComposition card={card}/>}<StaticDiagram card={card} hide={fill&&!battery}/><ol><li>{battery?"負極で起こる半反応式":"陽極で起こる半反応式"}を書きなさい。</li><li>{battery?"正極で起こる半反応式":"陰極で起こる半反応式"}を書きなさい。</li><li>全体の反応式を書きなさい。</li><li>電子の移動方向を答えなさい。</li><li>各電極の生成物と質量変化を答えなさい。</li><li>溶液の濃度・色・液性はどのように変化するか。</li></ol><div className="answer-lines">{[battery?"負極反応":"陽極反応",battery?"正極反応":"陰極反応","全反応式","電子の流れ","生成物・質量変化","溶液変化"].map(label=><p key={label}><b>{label}：</b></p>)}</div></article>}
function AnswerPage({card,index}:{card:ElectrochemistryCard;index:number}){const anode=card.electrodes.find(item=>item.electrodeRole==="anode")!,cathode=card.electrodes.find(item=>item.electrodeRole==="cathode")!,battery=isBattery(card),negative=card.electrodes.find(item=>item.polarity==="negative")!,positive=card.electrodes.find(item=>item.polarity==="positive")!;return <article className="print-quiz-page answer-page"><header><h1>模範解答</h1><span>第{index+1}問</span></header><h2>{card.name}</h2>{battery&&<BatteryComposition card={card}/>}<StaticDiagram card={card} hide={false}/><dl><div><dt>{battery?"負極反応":"陽極反応"}（{battery?negative.reactionType==="oxidation"?"酸化":"還元":"酸化"}）</dt><dd>{battery?negative.equation:anode.equation}<small>{reactionReason(battery?negative:anode)}</small></dd></div><div><dt>{battery?"正極反応":"陰極反応"}（{battery?positive.reactionType==="oxidation"?"酸化":"還元":"還元"}）</dt><dd>{battery?positive.equation:cathode.equation}<small>{reactionReason(battery?positive:cathode)}</small></dd></div><div><dt>全反応</dt><dd>{card.overallEquation}</dd></div><div><dt>電子</dt><dd>{card.electronFlow}</dd></div><div><dt>質量変化</dt><dd>{card.electrodes.map(item=>`${item.label}：${massLabels[item.massChange]}`).join("／")}</dd></div><div><dt>溶液変化</dt><dd>{card.solutionChanges.join("／")}</dd></div><div><dt>重要ポイント</dt><dd>{card.keyPoints.join("／")}</dd></div><div className="mistake"><dt>よくある誤答</dt><dd>{card.commonMistakes.join("／")}</dd></div></dl></article>}

export function ElectrochemistryQuizGenerator(){const [scope,setScope]=useState<Scope>("both");const [range,setRange]=useState<"all"|"individual"|"random">("random");const [type,setType]=useState<QuestionType>("mixed");const [pages,setPages]=useState(1);const [selected,setSelected]=useState<string[]>(["daniel"]);const [seed,setSeed]=useState(1);const [printMode,setPrintMode]=useState<PrintMode>("problem");
 const eligible=useMemo(()=>electrochemistryCards.filter(card=>scope==="both"||(scope==="battery"?isBattery(card):!isBattery(card))),[scope]);const generated=useMemo(()=>{if(range==="individual")return eligible.filter(card=>selected.includes(card.id)).slice(0,pages);if(range==="all")return eligible.slice(0,pages);return Array.from({length:Math.min(pages,eligible.length)},(_,i)=>eligible[(i*5+seed)%eligible.length]);},[eligible,pages,range,seed,selected]);
 const print=(mode:PrintMode)=>{setPrintMode(mode);window.setTimeout(()=>window.print(),80);};return <div className="quiz-generator"><div className="quiz-generator-panel"><label>単元<select value={scope} onChange={e=>setScope(e.target.value as Scope)}><option value="battery">電池</option><option value="electrolysis">電気分解</option><option value="both">両方</option></select></label><label>出題範囲<select value={range} onChange={e=>setRange(e.target.value as typeof range)}><option value="individual">個別選択</option><option value="all">すべてから順番</option><option value="random">ランダム</option></select></label><label>形式<select value={type} onChange={e=>setType(e.target.value as QuestionType)}><option value="written">記述式</option><option value="fill">穴埋め式</option><option value="mixed">混合</option></select></label><label>ページ数<select value={pages} onChange={e=>setPages(Number(e.target.value))}>{[1,2,5,10].map(value=><option key={value}>{value}</option>)}</select></label>{range==="random"&&<button onClick={()=>setSeed(value=>value+1)}>問題を入れ替える</button>}<button onClick={()=>print("problem")}>問題PDF・印刷</button><button onClick={()=>print("answer")}>解答PDF・印刷</button></div>{range==="individual"&&<div className="quiz-card-picker">{eligible.map(card=><label key={card.id}><input type="checkbox" checked={selected.includes(card.id)} onChange={e=>setSelected(current=>e.target.checked?[...current,card.id]:current.filter(id=>id!==card.id))}/>{card.name}</label>)}</div>}<p className="pdf-note">「PDF・印刷」からブラウザの印刷画面を開き、送信先で「PDFに保存」を選べます。</p><div className={`printable-electrochemistry-quiz ${printMode}`}><div className="screen-preview"><h3>印刷プレビュー：{printMode==="problem"?"問題":"模範解答"}</h3></div>{generated.map((card,index)=>printMode==="problem"?<ProblemPage card={card} index={index} type={type} key={card.id}/>:<AnswerPage card={card} index={index} key={card.id}/>)}</div></div>}
